### ISSUE TITLE
Hex_table of version 1.7.36

### ISSUE THREAD

**Issue by andreloty** [gazzamc/starfield_hex_updater#1]
How can I generate the json hex_table to a new version of the game every time it's release?

**Comment by gazzamc** [comment]
Hi,

This isn't an automatic process, you first need to manually find all the hex values for the windows version of the game and then run the ``generate` mode against the updated steam version of sfse.

I have been busy since the new update for sfse to support 1.7.36 has been release, but I'm in the process of creating the hex_table, I'll hopefully have it up in the next day or two.

**Comment by gazzamc** [comment]
I've added a script to do just this, you can find it [here](https://github.com/gazzamc/starfield_hex_updater/tree/main/tools). I will close this issue now.

Alternatively, the [hex table](https://github.com/gazzamc/starfield_hex_updater/tree/main/hex_tables) is available now too
