### ISSUE TITLE
File placement

### ISSUE THREAD

**Issue by huntereby** [gazzamc/starfield_hex_updater#4]
Im confused on where all these files go SFSE, hex_updated? Can you be a little bit more specific on where we place these files with git clone?

**Comment by gazzamc** [comment]
If you're talking about the manual process, patching SFSE using `hex_updater.py` script, you don't place the files anywhere. Clone the repo and point the script to the location of the SFSE repo.

If you're talking about the Powershell script, just run the batch file. 

The only files you move are the game files and the generated SFSE files, if doing the patching manually otherwise the powershell script does this for you.

There is [documentation](https://github.com/gazzamc/starfield_hex_updater/tree/main/docs) with step-by-step process.
